version: "2.0"

services:
  api:
    image: "ake3m/api:$VERSION"
    ports:
      - 3002:3002
    environment:
      - "VIRTUAL_HOST=api.ake3m.com"
      - "LETSENCRYPT_HOST=api.ake3m.com"
      - "LETSENCRYPT_EMAIL=contact@ake3m.com"
      - "AKE3M_CMS_ACCESS_TOKEN=${AKE3M_CMS_ACCESS_TOKEN}"
      - "AKE3M_CMS_ENDPOINT=${AKE3M_CMS_ENDPOINT}"
      - "AKE3M_RECAPCHA_SECRET=${AKE3M_RECAPCHA_SECRET}"
      - "AKE3M_EMAIL=${AKE3M_EMAIL}"
      - "AKE3M_EMAIL_PASSWORD=${AKE3M_EMAIL_PASSWORD}"
  web:
    image: "ake3m/web:$VERSION"
    ports:
      - 3000:3000
    environment:
      - "VIRTUAL_HOST=ake3m.com,www.ake3m.com"
      - "LETSENCRYPT_HOST=ake3m.com,www.ake3m.com"
      - "LETSENCRYPT_EMAIL=contact@ake3m.com"
      - "API_URL=https://api.ake3m.com"
    depends_on:
      - api
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - $HOME/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
  letsenctypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - $HOME/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - proxy
